# Generated by Django 2.2.2 on 2019-06-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freind',
            new_name='Friend',
        ),
    ]
